version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth-task
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8081:8080